### PR TITLE
Include search content matches in CSV output

### PR DESCRIPTION
**Pull request by dobrou**
I find content matches in CSV export very useful.

I include only the matching part from the line preview.
This way, user can adjust output exactly as he wants.

Multiple results per line/file are simply concatenated by ' ' (space), to avoid dealing with newlines in cells so to keep CSV generator simple.

I dev tested change using local extension sideload and it works.

Tslint fix should also make master build green again.

### CODE REVIEW

**Comment by dobrou** [comment]
Hi @sqs , may I ask you for review of this PR?

**Comment by sqs** [comment]
Thank you. Sorry for missing it when you sent it up. I just asked our web team to review this. It looks good to me, but I want to make sure it gets proper review.

**Comment by dobrou** [comment]
Thank you.

**Review by tjkandala — APPROVED** [review]
Looks good to me too!

**Comment by sqs** [comment]
@tjkandala Thank you! Can you please merge this and re-publish this extension? @dobrou is an outside contributor, so they can't merge this.

**Pull request merged**
